### ISSUE TITLE
File renaming should not depend on previous action

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon2#1102]
In investigating #947 after not having uploaded to Neon in a long time, I found out renaming was trickier than I expected. 
It took me a while to work out that this was even possible under crtl+click (I think I was expecting either command-click or a click-once-and-wait sort of thing.) It ALSO took me a while to work out why I wasn't always getting to rename the file--while you always get a drop-down to open/rename/delete, you can only perform those actions if you have first clicked on the file in question THEN gotten to the dropdown. (That is, unless you've been right-clicking elsewhere on the screen, in which case right-clicking on the files continues to show you the options to upload document/create folder and not the file-specific actions).
Anyway, I would expect to either 1) always be able to rename the file (my preference) or 2) only be shown the option if I am able to rename, that is, after I've already selected a file. 

Also, a minor (not especially related) issue I discovered while playing with file names: the file type detection means that if I have a second copy of some unzipped MEI file, which often automatically get named up in Finder as something like "blah.mei 2", it won't allow upload because it detects a file type mismatch. I could just rename such a file on my end (or just use my first copy of it), so it's not a big issue. Mentioning it here so someone can say why this is not worth changing and I should just rename files to be the right format.

**Comment by annamorphism** [comment]
maybe I should be patient and wait for the version mentioned in #1084 to show up on production...

**Comment by yinanazhou** [comment]
Hi @annamorphism we have pushed the changes.

**Comment by annamorphism** [comment]
@yinanazhou hmm, now if I haven't selected a folder but ctrl+click I can still get the option to rename, but the popup is empty and neither "confirm" nor "cancel" does anything...
<img width="444" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/8a7ca880-7645-4be5-8156-019d7f4221a7">

**Comment by yinanazhou** [comment]
oops, it works for right click. I'll fix ctrl+click soon. Sorry for the confusion.

**Comment by yinanazhou** [comment]
Hi! Forgot to update here that I've pushed the changes.

**Comment by yinanazhou** [comment]
Hi @annamorphism, could you please confirm that this issue has been fixed? Thanks!

**Comment by annamorphism** [comment]
@yinanazhou there's still something a little quirky--I can successfully rename if I only use arrow keys (so, for example, I delete the name when it's highlighted, or use the right arrow to put my cursor at the end of the name and add a character), but if I click on the name field nothing happens (and I also lose the arrow-key control, so I just have to close the pop-up and try again.)

**Comment by yinanazhou** [comment]
Which browser are you using?

**Comment by annamorphism** [comment]
This is in Firefox--haven't tested what happens in other browsers yet.

**Comment by yinanazhou** [comment]
I could reproduce this issue in safari and firefox a few minutes ago, but now I cannot reproduce this issue in them anymore... @annamorphism could you reproduce it now?

**Comment by annamorphism** [comment]
@yinanazhou yes--I didn't get it at first, but after I opened and closed a "new upload" window it seemed to occur again.

**Comment by yinanazhou** [comment]
Hi @annamorphism I've pushed the changes.

**Comment by annamorphism** [comment]
Looks like the issue is fixed! Closing.
