### ISSUE TITLE
[Neon staging] Reloading the page makes all glyphs disappear

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1224]
If you open a folio on staging, make any sort of change, and then reload the page, the page reloads but the glyphs never reappear. It doesn't make a difference whether you save or not before reloading the page. Neon also becomes partially unresponsive, so only some of the buttons and sliders are clickable.

**Comment by JoyfulGen** [comment]
UPDATE: If you save your work, go to the dashboard, and reopen the same file, the same thing happens. I haven't yet found a way to leave a file and come back to it without the glyphs disappearing.

**Comment by yinanazhou** [comment]
Thought I fixed #1217

**Comment by yinanazhou** [comment]
Does this still happen for the folios you recently uploaded to staging?

**Comment by JoyfulGen** [comment]
It does, but only on Firefox! I just tried on Chrome and there's no problem there. Is this a me problem then?

**Comment by yinanazhou** [comment]
I've pushed the changes to neon staging.

**Comment by JoyfulGen** [comment]
The same thing is still happening :( Is my Firefox just ruining everything?

**Comment by yinanazhou** [comment]
It's happening again to my firefox too...I'll have a look. I don't like firefox anymore :(

**Comment by yinanazhou** [comment]
I cannot reproduce this locally :(

**Comment by JoyfulGen** [comment]
This is fixed! Closing issue now.
