### ISSUE TITLE
[Staging] Clef misbehaviours 

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1248]
A pitch of a newly inserted glyph is calculated assuming top line as c4, but the glyph is placed based on the clef.
Expected behaviour:
The pitch should be calculated based on the clef.

**Comment by yinanazhou** [comment]
Hi @fujinaga, @JoyfulGen, and @annamorphism , I would like to confirm with you where the default clef should be when there is no clef found. Should it be:
1. Use the last clef we can find from previous staves; or
2. Set the top line as C4

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, staging should be good after the changes get merged.

**Comment by JoyfulGen** [comment]
> Hi @fujinaga, @JoyfulGen, and @annamorphism , I would like to confirm with you where the default clef should be when there is no clef found. Should it be:
> 
>     1. Use the last clef we can find from previous staves; or
> 
>     2. Set the top line as C4

I think at the meeting we agreed for option 1! @annamorphism can confirm. I do have a question though: what will happen when the missing clef is at the top of the page and there's no clef on a previous staff? Will the default clef then be top line C4?

**Comment by annamorphism** [comment]
good catch! I think it does make sense to have the top line as the clef iff there is no "previous staff."

**Comment by fujinaga** [comment]
Is the top line for the c-clef the most common position?

**Comment by JoyfulGen** [comment]
I've found another clef misbehaviour: F clefs aren't happy. If you put an F clef on a staff without a clef or after a C clef, all the glyphs after the new F clef jump up an octave. Their pitch is then correctly calculated based on the new F clef.

Demo:

https://github.com/user-attachments/assets/47039a4c-5c7b-4724-94c4-ee5ac8ffe26d

You can see that the glyphs on the staff below are also jumping, because they don't have a clef, so their default clef is the one on the previous staff.

**Comment by JoyfulGen** [comment]
@yinanazhou I found another one: if a staff doesn't have any on it and also no clef before it, I can't move any element: I can click and drag them around, but they don't snap to a staff line or space properly. And if I undo the moving action, the previous action undoes as well, so it looks like Neon isn't registering the moving at all.

Demo (I move the staff first so that you can see what the undo button does):

Uploading Can't move elements without clef.mov…

**Comment by yinanazhou** [comment]
@JoyfulGen this should be fixed by now!

**Comment by JoyfulGen** [comment]
@yinanazhou I can move elements on a staff without a clef now! The F clef issue is still there though, but different: now if I add an F clef to a staff, the neumes on that staff stay put, but the neumes on the staves below jump.

**Comment by yinanazhou** [comment]
Update: neumes below also jump when I moved a clef...the shape of clef doesn't really matter.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, the elements jump on inserting clef should now be fixed on staging! (They still jump a bit on dragging now, but I will fix that in #1250 and #1252 . I think they might be caused by the same bug.) Could you please verify and close this issue if the insertion is working as expected?

**Comment by JoyfulGen** [comment]
@yinanazhou it looks good! Closing issue now.
